module BaseStats
    BASE_HEALTH = 20
    BASE_STRENGTH = 5
    BASE_INTELLIGENCE = 0
    BASE_AGILITY = 10

    NB_STATS_PER_LEVEL = 2

    HEALTH_UPGRADE_PER_LEVEL = 2
    STRENGTH_UPGRADE_PER_LEVEL = 2
    INTELLIGENCE_UPGRADE_PER_LEVEL = 3
    AGILITY_UPGRADE_PER_LEVEL = 2

    LEVELS_PER_EXTRA_MONSTER = 3
end
