module Monsters
    # Female
    GOBLIN_F = "gobline"
    SPIDER_F = "araignée"
    BAT_F = "chauve-sourie"
    HARPIE_F = "harpie"
    ZOMBIE_F = "mort-vivante"
    PRISONNER_F = "prisonnière oubliée"
    # Male
    GOBLIN_M = "goblin"
    SLIME_M = "slime"
    ZOMBIE_M = "mort-vivant"
    SPRIGGAN_M = "spriggan"
    SKELLETON_M = "squelette"
    PRISONNER_M = "prisonnier oublié"
end

module Rooms
    # Female
    ROOM_F = "salle"
    ALCOVE_F = "pièce"
    CHAMBER_F = "chambre"
    CELL_F = "cellule"
    TORTURE_CHAMBER_F = "chambre de torture"
    GEOLLE_F = "geolle"
    # Male
    CORRIDOR_M = "couloir"
    TUNNEL_M = "tunnel"
    REFECTORY_M = "réfectoire"
    SLEEP_PLACE_M = "dortoir"
end

module Adjectives
    # Female
    SMALL_F = "petite"
    BIG_F = "grosse"
    TALL_F = "grande"
    SCARY_F = "terrifiante"
    SPACIOUS_F = "spacieuse"
    LONG_F = "longue"
    MUSCULAR_F = "musclée"
    WORRIED_F = "inquiète"
    WORRYING_F = "inquiétante"
    TIRED_F = "fatiguée"
    ANGRY_F = "énervée"
    WARY_F = "méfiante"
    GREEN_F = "verte"
    BLUISH_F = "bleutée"
    GREYISH_F = "grisée"
    SMART_F = "intelligente"
    AGILE_F = "agile"
    JADED_F = "blasée"
    SCOUT_F = "éclaireuse"
    AUTHORITARIAN_F = "authoritaire"
    COLD_F = "froide"
    HUMID_F = "humide"
    ISOLATED_F = "isolée"
    DARK_F = "sombre"
    ANCIENT_F = "ancienne"
    NARROW_F = "étroite"
    DRY_F = "sèche"
    DUSTY_F = "poussièreuse"
    SILENT_F = "silencieuse"
    STRANGE_F = "étrange"
    RUINED_F = "en ruine"
    # Male
    SMALL_M = "petit"
    BIG_M = "gros"
    TALL_M = "grand"
    SCARY_M = "terrifiant"
    SPACIOUS_M = "spacieux"
    LONG_M = "long"
    MUSCULAR_M = "musclé"
    WORRIED_M = "inquiet"
    WORRYING_M = "inquiétant"
    TIRED_M = "fatigué"
    ANGRY_M = "énervé"
    WARY_M = "méfiant"
    GREEN_M = "vert"
    BLUISH_M = "bleuté"
    GREYISH_M = "grisé"
    SMART_M = "intelligent"
    AGILE_M = "agile"
    JADED_M = "blasé"
    SCOUT_M = "éclaireur"
    AUTHORITARIAN_M = "authoritaire"
    COLD_M = "froid"
    HUMID_M = "humide"
    ISOLATED_M = "isolé"
    DARK_M = "sombre"
    ANCIENT_M = "ancien"
    NARROW_M = "étroit"
    DRY_M = "sec"
    DUSTY_M = "poussiéreux"
    SILENT_M = "silencieux"
    STRANGE_M = "étrange"
    RUINED_M = "en ruine"
end
